version: '3'

services:
  polly:
    container_name: polly
    image: polly:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      IMAGE: "polly"
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - .env
